[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "wok"
version = "0.1.0"
description = "Wok is a tool to manage several `git` repos in a single workspace."
authors = ["Serge Matveenko <lig@countzero.co>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-black = "^0.3.7"
pytest-flake8 = "^1.0.4"
pytest-isort = "^0.3.1"
pytest-mypy = "^0.4.2"
